version: '3.0'
services:
  expressserver:
    # image: express-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/usr/app/.env
    ports:
      - '8000:8000'
